categories:
  sponsoring:
    label: 'sponsoring'
  sponsoring.templates:
    label: 'Templates'
    parent: sponsoring
  sponsoring.pages:
    label: 'Pages'
    parent: sponsoring
  sponsoring.settings:
    label: 'Settings'
    parent: sponsoring
settings:
  sponsoring.templateRootPath:
    label: 'Templates'
    category: sponsoring.templates
    description: 'Path to template root'
    type: string
    default: 'EXT:sponsoring/Resources/Private/Templates/'
  sponsoring.partialRootPath:
    label: 'Partials'
    category: sponsoring.templates
    description: 'Path to partial root'
    type: string
    default: 'EXT:sponsoring/Resources/Private/Partials/'
  sponsoring.layoutRootPath:
    label: 'Layouts'
    category: sponsoring.templates
    description: 'Path to layout root'
    type: string
    default: 'EXT:sponsoring/Resources/Private/Layouts/'
  sponsoring.storagePid:
    label: 'Default storage PID'
    category: sponsoring.settings
    description: 'Folder that stores all POIs'
    type: int
    default: 0
