categories:
  statictagcloud:
    label: 'static-tag-cloud'
  statictagcloud.templates:
    label: 'Templates'
    parent: statictagcloud
  statictagcloud.pages:
    label: 'Pages'
    parent: statictagcloud
  statictagcloud.settings:
    label: 'Settings'
    parent: statictagcloud
settings:
  statictagcloud.templateRootPath:
    label: 'Templates'
    category: statictagcloud.templates
    description: 'Path to template root'
    type: string
    default: 'EXT:statictagcloud/Resources/Private/Templates/'
  statictagcloud.partialRootPath:
    label: 'Partials'
    category: statictagcloud.templates
    description: 'Path to partial root'
    type: string
    default: 'EXT:statictagcloud/Resources/Private/Partials/'
  statictagcloud.layoutRootPath:
    label: 'Layouts'
    category: statictagcloud.templates
    description: 'Path to layout root'
    type: string
    default: 'EXT:statictagcloud/Resources/Private/Layouts/'
  statictagcloud.storagePid:
    label: 'Default storage PID'
    category: statictagcloud.settings
    description: 'Folder that stores all POIs'
    type: int
    default: 0
